version: "3.8"

services:
# lib
  lib:
    image: lib:latest
    container_name: lib
    build:
      context: ./lib
      dockerfile: Dockerfile
    command: npm run build
    networks:
      - nestjs-network

# gateway
  gateway:
    image: gateway:latest
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - user-service
      - recipes-service
      - auth-service
    networks:
      - nestjs-network

# auth-service
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=recipes_service_db
    depends_on:
      - mysql
    networks:
      - nestjs-network

# user-service
  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=foody_user
    depends_on:
      - mysql
    networks:
      - nestjs-network

# recipes-service
  recipes-service:
    image: recipes-service:latest
    container_name: recipes-service
    build:
      context: ./recipes-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=foody_recipes
    depends_on:
      - mysql
    networks:
      - nestjs-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
